sonar.host.url=http://localhost:9000

sonar.projectKey=InkWell-Frontend
sonar.projectName=InkWell-Frontend

sonar.token=sqp_a76090ce8761e2b7e1cf8e11c4e556612e414d12

sonar.sources=src

sonar.tests=src
sonar.test.inclusions=src/**/*.test.jsx,src/**/*.test.tsx


sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8

# Optional but good
sonar.exclusions=node_modules/**,dist/**,src/assets/**